# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a70b119ca4194b7aef4d443618f6d28392b3c3e0178de622e2b445dc71067e7420d9532dde15c69827cb161ecf0da6c1631dbcac8aa1df9e060e5ffc827d0e8d

test:
  secret_key_base: 77c98c41b4f58f6b7b0d3a574ac3ab97d1fb189b42a0589585bb2683a90785102ffea78fb59397c95ebfa408ad41d542a3c1d9f6c7bc79d0b4ae0d057ac9d2b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
